"""initial case desk schema

Revision ID: f5b9059aae3f
Revises:
Create Date: 2026-09-04 10:27:14.551331
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f5b9059aae3f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inbound_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("msgid", sa.String(length=256), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_inbound_messages_msgid"), "inbound_messages", ["msgid"], unique=True)
    op.create_table(
        "stored_media",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("object_key", sa.String(length=1024), nullable=False),
        sa.Column("mime_type", sa.String(length=256), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("object_key", name="uq_stored_media_object_key"),
    )
    op.create_index(op.f("ix_stored_media_sha256"), "stored_media", ["sha256"], unique=False)
    op.create_table(
        "teams",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("consult_queue", "dev", name="teamkind", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("wecom_userid", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=256), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_wecom_userid"), "users", ["wecom_userid"], unique=True)
    op.create_table(
        "web_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index("ix_web_sessions_active", "web_sessions", ["user_id", "expires_at"])
    op.create_index(op.f("ix_web_sessions_expires_at"), "web_sessions", ["expires_at"])
    op.create_index(op.f("ix_web_sessions_token_hash"), "web_sessions", ["token_hash"], unique=True)
    op.create_index(op.f("ix_web_sessions_user_id"), "web_sessions", ["user_id"])
    op.create_table(
        "cases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_ref", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column(
            "lifecycle_status",
            sa.Enum("open", "closed", name="lifecyclestatus", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "waiting_on",
            sa.Enum("consult", "dev", "none", name="waitingon", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("consult_queue_id", sa.Uuid(), nullable=False),
        sa.Column("current_consultant_id", sa.Uuid(), nullable=True),
        sa.Column("current_dev_team_id", sa.Uuid(), nullable=False),
        sa.Column("current_developer_id", sa.Uuid(), nullable=True),
        sa.Column("creator_id", sa.Uuid(), nullable=False),
        sa.Column("related_case_id", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("last_entry_sequence", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("last_entry_sequence >= 0", name="ck_cases_sequence_nonnegative"),
        sa.CheckConstraint(
            "(lifecycle_status = 'closed' AND waiting_on = 'none') OR "
            "(lifecycle_status = 'open' AND waiting_on IN ('consult', 'dev'))",
            name="ck_cases_lifecycle_waiting_consistent",
        ),
        sa.CheckConstraint("version >= 1", name="ck_cases_version_positive"),
        sa.ForeignKeyConstraint(
            ["consult_queue_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["current_consultant_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["current_dev_team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["current_developer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["related_case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_ref", name="uq_cases_case_ref"),
    )
    op.create_index(op.f("ix_cases_consult_queue_id"), "cases", ["consult_queue_id"], unique=False)
    op.create_index(
        op.f("ix_cases_current_consultant_id"), "cases", ["current_consultant_id"], unique=False
    )
    op.create_index(
        op.f("ix_cases_current_dev_team_id"), "cases", ["current_dev_team_id"], unique=False
    )
    op.create_index(
        op.f("ix_cases_current_developer_id"), "cases", ["current_developer_id"], unique=False
    )
    op.create_table(
        "message_drafts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("source_msgid", sa.String(length=256), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_msgid", name="uq_message_drafts_source_msgid"),
    )
    op.create_index(
        op.f("ix_message_drafts_expires_at"), "message_drafts", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_message_drafts_owner_user_id"), "message_drafts", ["owner_user_id"], unique=False
    )
    op.create_table(
        "team_memberships",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("member", "admin", name="membershiprole", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("team_id", "user_id"),
    )
    op.create_table(
        "wecom_channels",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("chatid", sa.String(length=256), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("initialized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chatid", name="uq_wecom_channels_chatid"),
    )
    op.create_index(
        "ix_wecom_channels_active_team", "wecom_channels", ["team_id", "active"], unique=False
    )
    op.create_table(
        "case_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "formal_message",
                "transfer_consultant",
                "transfer_developer",
                "transfer_dev_team",
                "closed",
                "reopened",
                "correction",
                name="caseentrykind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "side",
            sa.Enum("consult", "dev", "system", name="entryside", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_name_snapshot", sa.String(length=256), nullable=False),
        sa.Column(
            "message_intent",
            sa.Enum("handoff", "sync", name="messageintent", native_enum=False, length=32),
            nullable=True,
        ),
        sa.Column("source_msgid", sa.String(length=256), nullable=True),
        sa.Column("corrects_entry_id", sa.Uuid(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["corrects_entry_id"],
            ["case_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "sequence", name="uq_case_entries_case_sequence"),
        sa.UniqueConstraint("source_msgid", name="uq_case_entries_source_msgid"),
    )
    op.create_index(
        "ix_case_entries_case_sequence", "case_entries", ["case_id", "sequence"], unique=False
    )
    op.create_table(
        "message_draft_parts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("draft_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("text", "image", name="partkind", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("media_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "(kind = 'text' AND text IS NOT NULL AND media_id IS NULL) "
            "OR (kind = 'image' AND media_id IS NOT NULL AND text IS NULL)",
            name="ck_message_draft_parts_payload_matches_kind",
        ),
        sa.CheckConstraint("position >= 0", name="ck_message_draft_parts_nonnegative_position"),
        sa.ForeignKeyConstraint(["draft_id"], ["message_drafts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["stored_media.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("draft_id", "position", name="uq_message_draft_parts_draft_position"),
    )
    op.create_table(
        "case_entry_parts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entry_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("text", "image", name="partkind", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("media_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "(kind = 'text' AND text IS NOT NULL AND media_id IS NULL) "
            "OR (kind = 'image' AND media_id IS NOT NULL AND text IS NULL)",
            name="ck_case_entry_parts_payload_matches_kind",
        ),
        sa.CheckConstraint("position >= 0", name="ck_case_entry_parts_nonnegative_position"),
        sa.ForeignKeyConstraint(["entry_id"], ["case_entries.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["stored_media.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entry_id", "position", name="uq_case_entry_parts_entry_position"),
    )
    op.create_table(
        "deliveries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entry_id", sa.Uuid(), nullable=False),
        sa.Column(
            "destination_type",
            sa.Enum("user", "chat", name="deliverydestination", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("destination_address", sa.String(length=256), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "sent", "failed", name="deliverystatus", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "waiting_on_after_delivery",
            sa.Enum("consult", "dev", "none", name="waitingon", native_enum=False, length=32),
            nullable=True,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("lock_token", sa.Uuid(), nullable=True),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["entry_id"], ["case_entries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_deliveries_entry", "deliveries", ["entry_id"], unique=False)
    op.create_index(op.f("ix_deliveries_lock_token"), "deliveries", ["lock_token"], unique=False)
    op.create_index(
        "ix_deliveries_pending", "deliveries", ["status", "next_attempt_at"], unique=False
    )
    op.create_table(
        "delivery_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("delivery_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("text", "image", name="partkind", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("req_id", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "sent", "failed", name="deliveryitemstatus", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("platform_result_json", sa.JSON(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("position >= 0", name="ck_delivery_items_nonnegative_position"),
        sa.ForeignKeyConstraint(["delivery_id"], ["deliveries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("delivery_id", "position", name="uq_delivery_items_delivery_position"),
        sa.UniqueConstraint("req_id", name="uq_delivery_items_req_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("delivery_items")
    op.drop_index("ix_deliveries_pending", table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_lock_token"), table_name="deliveries")
    op.drop_index("ix_deliveries_entry", table_name="deliveries")
    op.drop_table("deliveries")
    op.drop_table("case_entry_parts")
    op.drop_table("message_draft_parts")
    op.drop_index("ix_case_entries_case_sequence", table_name="case_entries")
    op.drop_table("case_entries")
    op.drop_index("ix_wecom_channels_active_team", table_name="wecom_channels")
    op.drop_table("wecom_channels")
    op.drop_table("team_memberships")
    op.drop_index(op.f("ix_message_drafts_owner_user_id"), table_name="message_drafts")
    op.drop_index(op.f("ix_message_drafts_expires_at"), table_name="message_drafts")
    op.drop_table("message_drafts")
    op.drop_index(op.f("ix_cases_current_developer_id"), table_name="cases")
    op.drop_index(op.f("ix_cases_current_dev_team_id"), table_name="cases")
    op.drop_index(op.f("ix_cases_current_consultant_id"), table_name="cases")
    op.drop_index(op.f("ix_cases_consult_queue_id"), table_name="cases")
    op.drop_table("cases")
    op.drop_index(op.f("ix_web_sessions_user_id"), table_name="web_sessions")
    op.drop_index(op.f("ix_web_sessions_token_hash"), table_name="web_sessions")
    op.drop_index(op.f("ix_web_sessions_expires_at"), table_name="web_sessions")
    op.drop_index("ix_web_sessions_active", table_name="web_sessions")
    op.drop_table("web_sessions")
    op.drop_index(op.f("ix_users_wecom_userid"), table_name="users")
    op.drop_table("users")
    op.drop_table("teams")
    op.drop_index(op.f("ix_stored_media_sha256"), table_name="stored_media")
    op.drop_table("stored_media")
    op.drop_index(op.f("ix_inbound_messages_msgid"), table_name="inbound_messages")
    op.drop_table("inbound_messages")
    # ### end Alembic commands ###
